[tox]
env_list =
    py{311,312,313,314}
isolated_build = True

[testenv]
description =
    run tests
extras = tests
allowlist_externals =
    hstcal
commands_pre =
    pip freeze
commands =
    pytest -v {posargs}
