
# AUTOMATICALLY GENERATED BY 'RECON':
# * DO NOT EDIT THIS MODULE MANUALLY.
# * DO NOT COMMIT THIS MODULE TO YOUR GIT REPOSITORY

__all__ = [
    '__version__',
    '__version_post__',
    '__version_commit__',
    '__version_date__',
    '__version_dirty__',
    '__build_date__',
    '__build_status__'
]

__version__ = '1.3.1'
__version_post__ = '0'
__version_commit__ = '4452148a'
__version_date__ = '2016-03-07 02:58:09 +0000'
__version_dirty__ = True
__build_date__ = '2016-03-29'
__build_time__ = '13:45:33.470560'
__build_status__ = 'release' if not int(__version_post__) > 0 \
    and not __version_dirty__ \
    else 'development'
