
# AUTOMATICALLY GENERATED BY 'RELIC':
# * DO NOT EDIT THIS MODULE MANUALLY.
# * DO NOT COMMIT THIS MODULE TO YOUR GIT REPOSITORY

__all__ = [
    '__version__',
    '__version_short__',
    '__version_long__',
    '__version_post__',
    '__version_commit__',
    '__version_date__',
    '__version_dirty__',
    '__build_date__',
    '__build_status__'
]

__version__ = 'v1.3.2.dev3'
__version_short__ = 'v1.3.2'
__version_long__ = 'v1.3.2-3-g022d3b8c-dirty'
__version_post__ = '3'
__version_commit__ = '022d3b8c'
__version_date__ = '2016-07-01 15:27:18 -0400'
__version_dirty__ = True
__build_date__ = '2016-07-01'
__build_time__ = '16:42:04.914518'
__build_status__ = 'release' if not int(__version_post__) > 0 \
    and not __version_dirty__ \
    else 'development'
