
# AUTOMATICALLY GENERATED BY 'RELIC':
# * DO NOT EDIT THIS MODULE MANUALLY.
# * DO NOT COMMIT THIS MODULE TO YOUR GIT REPOSITORY

__all__ = [
    '__version__',
    '__version_short__',
    '__version_long__',
    '__version_post__',
    '__version_commit__',
    '__version_date__',
    '__version_dirty__',
    '__build_date__',
    '__build_status__'
]

__version__ = '1.3.1.dev5'
__version_short__ = '1.3.1'
__version_long__ = '1.3.1-5-g881cda1d-dirty'
__version_post__ = '5'
__version_commit__ = '881cda1d'
__version_date__ = '2016-06-23 10:40:59 -0400'
__version_dirty__ = True
__build_date__ = '2016-06-25'
__build_time__ = '20:44:09.906684'
__build_status__ = 'release' if not int(__version_post__) > 0 \
    and not __version_dirty__ \
    else 'development'
