name: tests

on:
  push:
    branches:
      - main
      - '*x'
    tags:
      - '*'
  pull_request:
  schedule:
    # Weekly Wednesday 9AM build
    - cron: "0 9 * * 3"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    uses: zacharyburnett/github-actions-workflows/.github/workflows/tox.yml@install_conda_packages_directly
    with:
      conda_packages: |
        hstcal
      envs: |
        - linux: py311
        - linux: py312
        - macos: py313
        # https://github.com/OpenAstronomy/github-actions-workflows/issues/342
        #- linux: py314
